start_date: '1850-01-01'
end_date: '2100-12-31'
dt:
  1 # dt is currently hardcoded in the package as 1 day
  # changing this variable won't change anything until
  # we update the underlying package
forcing:
  POP_units: True
  use_cyclic_forcing: False
  streams:
    - forcing_streams/CESM2_LENS/TEMP.TL319_g17.yaml
    - forcing_streams/CESM2_LENS/TEMP_bottom.TL319_g17.yaml
    - forcing_streams/CESM2_LENS/POC_FLUX_bottom.TL319_g17.yaml
    - forcing_streams/CESM2_LENS/mesozoo_loss_zint_100m.TL319_g17.yaml
    - forcing_streams/CESM2_LENS/mesozooC_zint_100m.TL319_g17.yaml
max_output_time_dim: 365
method: euler
num_workers: 12
chunks:
  nlat: 128 # divide into 384
  nlon: 80 # divide into 320
initial_conditions:
  root_dir: /glade/campaign/cesm/development/bgcwg/projects/CESM2-OMIP2-like-4p2z-run/FEISTY_ic
  ic_file: companion_spinup.0125-12-31.zarr
output:
  diagnostic_names:
    - fish_yield
    - production
  overwrite: True
  hist_file: CESM2-LENS.1001.001_1850.zarr
  rest_file: CESM2-LENS.1001.001_1850-12-31.zarr
  hist_dir: ./
  rest_dir: ./
# Option to pull out a single lat,lon from POP grid
# (could we provide degrees instead of indices?)
# lat_lon: # lat: 0 - 383 on the 1 degree grid; lon: 0 - 319 on the 1 degree grid
#   - 0, 10
#   - 55, 20
